name: filmr
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  font_awesome_flutter: ^10.7.0
  youtube_player_flutter: ^8.1.1
  animated_splash_screen: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_lints: 4.0.0
  # flutter pub run flutter_launcher_icons
  flutter_launcher_icons: 0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path_android: assets/android_logo.png
  image_path_ios: assets/ios_logo.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
